// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEllH0UXSgX5HQ1Hkg3TA_dowbFx-99I',
    appId: '1:748808585022:web:de1a2133eba942d7db766f',
    messagingSenderId: '748808585022',
    projectId: 'my-profile-interview',
    authDomain: 'my-profile-interview.firebaseapp.com',
    storageBucket: 'my-profile-interview.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2boEa_8YT3ZQ3V1_-fHhT7KF-WDGdIGA',
    appId: '1:748808585022:android:77535b62608d7ffedb766f',
    messagingSenderId: '748808585022',
    projectId: 'my-profile-interview',
    storageBucket: 'my-profile-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntgZhexDiWtIGnLGENghbkma0z4JG-Ds',
    appId: '1:748808585022:ios:2c4e971e2c95d44cdb766f',
    messagingSenderId: '748808585022',
    projectId: 'my-profile-interview',
    storageBucket: 'my-profile-interview.appspot.com',
    androidClientId: '748808585022-it0hk78grq7p7dngdr9vukm65bug418i.apps.googleusercontent.com',
    iosClientId: '748808585022-4572kaq0i4l0hra76hcqqf56jndfap5l.apps.googleusercontent.com',
    iosBundleId: 'com.ingenious.myprofile.myProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntgZhexDiWtIGnLGENghbkma0z4JG-Ds',
    appId: '1:748808585022:ios:4686535136930e82db766f',
    messagingSenderId: '748808585022',
    projectId: 'my-profile-interview',
    storageBucket: 'my-profile-interview.appspot.com',
    androidClientId: '748808585022-it0hk78grq7p7dngdr9vukm65bug418i.apps.googleusercontent.com',
    iosClientId: '748808585022-a9405sd41mgeskc55lq3ld7n30bu9msq.apps.googleusercontent.com',
    iosBundleId: 'com.ingenious.myprofile.myProfile.RunnerTests',
  );
}
